# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'etsy_qt_interface_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(414, 326)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 381, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")


        self.root_parent_vbox = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.root_parent_vbox.setContentsMargins(0, 0, 0, 0)
        self.root_parent_vbox.setObjectName("root_parent_vbox")
        self.route_search_bar = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.route_search_bar.setObjectName("route_search_bar")
        self.root_parent_vbox.addWidget(self.route_search_bar)
        self.interface_parent_hbox = QtWidgets.QHBoxLayout()
        self.interface_parent_hbox.setObjectName("interface_parent_hbox")
        self.interface_controls_hbox = QtWidgets.QVBoxLayout()
        self.interface_controls_hbox.setObjectName("interface_controls_hbox")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.interface_controls_hbox.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.interface_controls_hbox.addWidget(self.pushButton_3)
        self.horizontalSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.interface_controls_hbox.addWidget(self.horizontalSlider)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.interface_controls_hbox.addWidget(self.pushButton)
        self.interface_parent_hbox.addLayout(self.interface_controls_hbox)


        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tree_tab = QtWidgets.QWidget()
        self.tree_tab.setObjectName("tree_tab")
        self.treeView = QtWidgets.QTreeView(self.tree_tab)
        self.treeView.setGeometry(QtCore.QRect(0, 20, 256, 192))
        self.treeView.setObjectName("treeView")
        self.tabWidget.addTab(self.tree_tab, "")
        self.table_tab = QtWidgets.QWidget()
        self.table_tab.setObjectName("table_tab")
        self.table = QtWidgets.QTableView(self.table_tab)
        self.table.setGeometry(QtCore.QRect(10, 0, 256, 192))
        self.table.setObjectName("table")
        self.tabWidget.addTab(self.table_tab, "")


        self.interface_parent_hbox.addWidget(self.tabWidget)
        self.root_parent_vbox.addLayout(self.interface_parent_hbox)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_2.setText(_translate("Form", "PushButton"))
        self.pushButton_3.setText(_translate("Form", "PushButton"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tree_tab), _translate("Form", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.table_tab), _translate("Form", "Tab 2"))
